query services($projectId: String!) {
  project(id: $projectId) {
    services {
      edges {
        node {
          id
          name
          serviceInstances {
            edges {
              node {
                healthcheckPath
              }
            }
          }
        }
      }
    }
  }
}
